<?php

namespace AppBundle\Repository;

/**
 * TartasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TartasRepository extends \Doctrine\ORM\EntityRepository
{
}
